In [63]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)

In [64]:
df = pd.read_csv('Prayagraj_Traffic_Data.csv')
df.sample(25)

,record_id,timestamp,intersection_id,intersection_name,latitude,longitude,vehicle_count,average_speed,signal_cycle_time,green_time,yellow_time,red_time,weather_condition,day_of_week,is_holiday,event,pollution_level,car_count,bus_count,truck_count,motorcycle_count
7696,7512.0,2023-01-06 05:10:00,2.0,Katra,25.4550,81.8463,88.0,33.90,120.0,70.0,6.0,44.0,Clear,Friday,0.0,NaN,1.79,55.0,9.0,9.0,15.0
234,9551.0,2023-01-07 15:10:00,1.0,Civil Lines,25.4486,81.8333,98.0,33.57,120.0,63.0,4.0,53.0,Clear,Saturday,0.0,NaN,1.85,59.0,8.0,10.0,21.0
3804,2193.0,2023-01-02 12:30:00,3.0,Chowk,25.4314,81.8437,106.0,35.89,NaN,62.0,4.0,54.0,Heatwave,Monday,0.0,NaN,2.29,67.0,14.0,9.0,16.0
4207,215.0,2023-01-01 03:30:00,5.0,Naini Bridge,25.4088,81.8592,51.0,44.53,120.0,54.0,5.0,61.0,Clear,Sunday,1.0,NaN,1.00,35.0,4.0,6.0,6.0
7535,8640.0,2023-01-06 23:50:00,10.0,Minto Park,25.4352,81.8820,145.0,29.61,120.0,59.0,5.0,56.0,Clear,Friday,0.0,NaN,2.78,83.0,12.0,16.0,34.0
8683,8863.0,2023-01-07 03:40:00,3.0,Chowk,25.4314,81.8437,93.0,35.40,120.0,68.0,4.0,48.0,Clear,Saturday,0.0,NaN,1.85,53.0,10.0,8.0,NaN
6368,9021.0,2023-01-07 06:20:00,1.0,Civil Lines,25.4486,81.8333,45.0,43.59,120.0,59.0,3.0,58.0,Clear,Saturday,0.0,NaN,1.08,24.0,5.0,8.0,8.0
8079,9455.0,2023-01-07 13:30:00,5.0,Naini Bridge,25.4088,81.8592,58.0,39.37,120.0,58.0,6.0,56.0,Clear,Saturday,0.0,NaN,1.32,28.0,7.0,8.0,15.0
5357,8284.0,2023-01-06 18:00:00,4.0,Tagore Town,25.4675,81.8867,204.0,28.31,120.0,72.0,4.0,44.0,Clear,Friday,0.0,Local Market Fair,3.78,122.0,20.0,14.0,48.0
4166,5691.0,2023-01-04 22:50:00,1.0,Civil Lines,25.4486,81.8333,108.0,31.02,120.0,73.0,4.0,43.0,Clear,Wednesday,0.0,NaN,1.92,67.0,NaN,11.0,23.0
6011,6049.0,2023-01-05 04:40:00,9.0,MNNIT Gate,25.4920,81.8639,43.0,46.06,120.0,59.0,3.0,58.0,Clear,Thursday,1.0,NaN,1.02,20.0,7.0,4.0,12.0
40,993.0,2023-01-01 16:30:00,3.0,Chowk,25.4314,81.8437,43.0,31.42,120.0,65.0,2.0,53.0,Heavy Rain,Sunday,1.0,NaN,0.83,27.0,4.0,4.0,8.0
3830,4419.0,2023-01-04 01:30:00,9.0,MNNIT Gate,25.4920,81.8639,99.0,30.47,120.0,55.0,5.0,60.0,Fog,Wednesday,0.0,NaN,1.91,56.0,9.0,10.0,24.0
2200,1165.0,2023-01-01 19:20:00,5.0,Naini Bridge,25.4088,81.8592,59.0,36.35,120.0,50.0,6.0,64.0,Light Rain,Sunday,1.0,NaN,1.29,35.0,5.0,10.0,9.0
726,7575.0,2023-01-06 06:10:00,5.0,Naini Bridge,25.4088,81.8592,94.0,24.33,120.0,54.0,5.0,61.0,Heavy Rain,Friday,0.0,NaN,NaN,50.0,12.0,13.0,19.0
9731,3983.0,2023-01-03 18:20:00,3.0,Chowk,25.4314,NaN,222.0,25.53,120.0,70.0,4.0,46.0,Clear,Tuesday,0.0,NaN,3.74,148.0,14.0,18.0,42.0
8254,8083.0,2023-01-06 14:40:00,3.0,Chowk,25.4314,81.8437,89.0,27.08,120.0,62.0,4.0,54.0,Fog,Friday,0.0,Local Market Fair,1.57,52.0,7.0,7.0,23.0
2420,5836.0,2023-01-05 01:10:00,6.0,Allahabad Junction,25.4358,81.8307,79.0,36.85,120.0,71.0,6.0,43.0,Clear,Thursday,1.0,NaN,1.70,47.0,9.0,9.0,14.0
312,1383.0,2023-01-01 23:00:00,3.0,Chowk,25.4314,81.8437,50.0,43.81,120.0,68.0,6.0,46.0,Clear,Sunday,1.0,NaN,1.01,26.0,6.0,4.0,14.0
3246,5373.0,2023-01-04 17:30:00,3.0,NaN,25.4314,81.8437,209.0,25.26,120.0,92.0,5.0,23.0,Clear,Wednesday,0.0,NaN,4.23,119.0,25.0,16.0,49.0
6595,813.0,2023-01-01 13:30:00,3.0,Chowk,25.4314,81.8437,NaN,42.21,120.0,62.0,5.0,53.0,Clear,Sunday,1.0,NaN,1.14,27.0,6.0,6.0,16.0
102,1932.0,2023-01-02 08:10:00,2.0,Katra,25.4550,81.8463,149.0,29.48,120.0,56.0,5.0,59.0,Clear,Monday,0.0,NaN,3.13,83.0,16.0,17.0,33.0
2927,6796.0,2023-01-05 17:10:00,6.0,Allahabad Junction,25.4358,81.8307,131.0,33.88,120.0,60.0,5.0,55.0,Clear,Thursday,1.0,NaN,2.70,72.0,14.0,14.0,31.0
1269,2972.0,2023-01-03 01:30:00,2.0,Katra,25.4550,81.8463,72.0,41.34,120.0,56.0,5.0,59.0,Clear,Tuesday,0.0,NaN,1.21,42.0,4.0,7.0,19.0
8582,NaN,2023-01-01 07:10:00,5.0,Naini Bridge,25.4088,81.8592,102.0,37.23,120.0,59.0,4.0,57.0,Clear,Sunday,1.0,NaN,2.04,58.0,8.0,14.0,22.0

In [65]:
df.isnull().sum()

record_id              98
timestamp              97
intersection_id        92
intersection_name     117
latitude              106
longitude             116
vehicle_count         112
average_speed          74
signal_cycle_time     108
green_time             92
yellow_time            89
red_time              102
weather_condition      78
day_of_week            94
is_holiday            104
event                9220
pollution_level       105
car_count              97
bus_count              95
truck_count           106
motorcycle_count      100
dtype: int64

In [66]:
# Function to generate a unique random ID
def generate_unique_random_id(existing_ids, low=1, high=10000):
    while True:
        random_id = np.random.randint(low, high)
        if random_id not in existing_ids: 
            return random_id

# Assuming 'df' is your dfFrame
existing_ids = set(df['record_id'].dropna())  # Get existing Record IDs without missing values
df['record_id'] = df['record_id'].apply(
    lambda x: generate_unique_random_id(existing_ids) if pd.isnull(x) else x
)

# Convert 'timestamp' column to DateTime format and drop rows with missing timestamps
df['timestamp'] = pd.to_datetime(df['timestamp'], errors='coerce')
df.dropna(subset=['timestamp'], inplace=True)

In [67]:
# Mapping between intersection names and IDs
area_to_id_map = {
    'Allahabad Junction': 6, 'Naini Bridge': 5, 'Chowk': 3, 'Tagore Town': 4,
    'Katra': 2, 'Phaphamau': 7, 'Minto Park': 10, 'MNNIT Gate': 9, 
    'Civil Lines': 1, 'Jhunsi': 8
}

# Fill missing 'intersection_id' using 'intersection_name' mapping
df['intersection_id'] = df['intersection_name'].map(area_to_id_map).fillna(df['intersection_id'])

# Fill missing 'intersection_name' using reverse mapping from 'intersection_id'
df['intersection_name'] = df['intersection_id'].map({v: k for k, v in area_to_id_map.items()}).fillna(df['intersection_name'])

# Resulting df Frame
print(df)

       record_id           timestamp  intersection_id   intersection_name  \
0         9926.0 2023-01-07 21:20:00              6.0  Allahabad Junction
1         8595.0 2023-01-06 23:10:00              5.0        Naini Bridge
2          673.0 2023-01-01 11:10:00              3.0               Chowk
3         8744.0 2023-01-07 01:40:00              4.0         Tagore Town
4          316.0 2023-01-01 05:10:00              6.0  Allahabad Junction
...          ...                 ...              ...                 ...
10075     7564.0 2023-01-06 06:00:00              4.0         Tagore Town
10076     6662.0 2023-01-05 15:00:00              2.0               Katra
10077     3105.0 2023-01-03 03:40:00              5.0        Naini Bridge
10078     5489.0 2023-01-04 19:20:00              9.0          MNNIT Gate
10079     6335.0 2023-01-05 09:30:00              5.0        Naini Bridge

       latitude  longitude  vehicle_count  average_speed  signal_cycle_time  \
0       25.4358    81.8307           75.0          39.72              120.0
1       25.4088    81.8592          139.0          30.33              120.0
2       25.4314    81.8437           20.0          53.28              120.0
3       25.4675    81.8867           21.0          36.06              120.0
4       25.4358    81.8307           41.0          47.21              120.0
...         ...        ...            ...            ...                ...
10075   25.4675    81.8867           23.0          52.53              120.0
10076   25.4550    81.8463           34.0          53.72              120.0
10077   25.4088    81.8592           22.0          40.91              120.0
10078   25.4920    81.8639          273.0          21.58              120.0
10079   25.4088    81.8592          114.0          33.92              120.0

       green_time  yellow_time  red_time weather_condition day_of_week  \
0            63.0          4.0      53.0             Clear    Saturday
1            51.0          4.0      65.0             Clear      Friday
2            69.0          5.0      46.0             Clear      Sunday
3            59.0          4.0      57.0        Heavy Rain    Saturday
4             NaN          5.0      54.0             Clear      Sunday
...           ...          ...       ...               ...         ...
10075        50.0          5.0      65.0             Clear      Friday
10076        63.0          5.0      52.0             Clear    Thursday
10077        60.0          5.0      55.0               Fog     Tuesday
10078        82.0          4.0      34.0        Light Rain   Wednesday
10079        62.0          5.0      53.0             Clear    Thursday

       is_holiday              event  pollution_level  car_count  bus_count  \
0             0.0                NaN             1.21       48.0        4.0
1             0.0                NaN             2.86       89.0       13.0
2             1.0                NaN             0.34       15.0        1.0
3             0.0                NaN             0.54       12.0        4.0
4             1.0                NaN             0.86       26.0        6.0
...           ...                ...              ...        ...        ...
10075         0.0  Local Market Fair             0.43       14.0        2.0
10076         1.0                NaN             0.57       20.0        4.0
10077         0.0                NaN             0.41       13.0        0.0
10078         0.0                NaN             5.58      167.0       26.0
10079         1.0                NaN             2.34       68.0       10.0

       truck_count  motorcycle_count
0              6.0              17.0
1             17.0              20.0
2              2.0               2.0
3              2.0               3.0
4              2.0               7.0
...            ...               ...
10075          2.0               5.0
10076          0.0              10.0
10077          5.0               4.0
10078         32.0              48.0
10079         15.0              21.0

[9983 rows x 21 columns]

In [68]:
# Latitude Mapping
area_to_latitude_map = {
    'Allahabad Junction': 25.4358, 'Naini Bridge': 25.4088, 'Chowk': 25.4314, 'Tagore Town': 25.4675,
    'Katra': 25.4550, 'Phaphamau': 25.4945, 'Minto Park': 25.4352, 'MNNIT Gate': 25.4920, 
    'Civil Lines': 25.4486, 'Jhunsi': 25.4326
}

df['latitude'] = df['intersection_name'].map(area_to_latitude_map).fillna(df['latitude'])

# Longitude Mapping
area_to_longitude_map = {
    'Allahabad Junction': 81.8307, 'Naini Bridge': 81.8592, 'Chowk': 81.8437, 'Tagore Town': 81.8867,
    'Katra': 81.8463, 'Phaphamau': 81.8686, 'Minto Park': 81.8820, 'MNNIT Gate': 81.8639, 
    'Civil Lines': 81.8333, 'Jhunsi': 81.9061
}

df['longitude'] = df['intersection_name'].map(area_to_longitude_map).fillna(df['longitude'])

In [69]:
# Step 1: Calculate mean values for each intersection_name
mean_values = df.groupby('intersection_name')[['vehicle_count', 'pollution_level', 'car_count', 'bus_count', 'truck_count', 'motorcycle_count']].mean()

# Step 2: Fill missing values for the specified columns using mean values
for col in ['vehicle_count', 'pollution_level', 'car_count', 'bus_count', 'truck_count', 'motorcycle_count']:
    df[col] = df.apply(
        lambda row: mean_values.loc[row['intersection_name'], col] if pd.isnull(row[col]) else row[col], axis=1
    )

# Step 3: Fill missing values in 'average_speed' with the overall mean
df['average_speed'] = df['average_speed'].fillna(df['average_speed'].mean())

In [70]:
# Replace missing values in 'signal_cycle_time' with a constant value
df['signal_cycle_time'] = df['signal_cycle_time'].fillna(120.0)

# List of columns to fill with their mean
columns_to_fill = ['green_time', 'yellow_time', 'red_time']

# Replace missing values in each of these columns with their respective mean
for col in columns_to_fill:
    df[col] = df[col].fillna(df[col].mean())

In [71]:
# Replace missing values in 'weather_condition' with its mode
weather_mode = df['weather_condition'].mode()[0]  # Find the mode (most frequent value)
df['weather_condition'] = df['weather_condition'].fillna(weather_mode)

In [72]:
#  Define the mapping for days of the week
days_mapping = {
    'Monday': 1,
    'Tuesday': 2,
    'Wednesday': 3,
    'Thursday': 4,
    'Friday': 5,
    'Saturday': 6,
    'Sunday': 7
}

#  Replace the values in the 'day_of_week' column directly
df['day_of_week'] = df['day_of_week'].map(days_mapping)

In [73]:
#  Define the mapping dictionary
event_mapping = {
    np.nan: 0,  # Handle NaN explicitly
    'New Year Celebration': 1,
    'Roadwork': 2,
    'Local Market Fair': 3,
    'Accident': 4
}

#  Replace the values in the 'event' column directly
df['event'] = df['event'].map(event_mapping).fillna(0).astype(int)

In [74]:
# Extract day of the week from the 'timestamp' column
df['day_of_week'] = df['timestamp'].dt.day_name()

# Assign 'is_holiday' based on whether the day is Sunday
df['is_holiday'] = df['day_of_week'].map({"Sunday": 1}).fillna(0)

# Drop rows with any remaining missing values
df.dropna(inplace=True)

In [75]:
# Create the 'is_weekend' column based on the 'day_of_week' column
df['is_weekend'] = df['day_of_week'].map({'Saturday': 1, 'Sunday': 1}).fillna(0).astype(int)

# Extract the hour from the 'timestamp' column and create a new column 'hour_of_day'
df['hour_of_day'] = df['timestamp'].dt.hour

In [76]:
df.isnull().sum()

record_id            0
timestamp            0
intersection_id      0
intersection_name    0
latitude             0
longitude            0
vehicle_count        0
average_speed        0
signal_cycle_time    0
green_time           0
yellow_time          0
red_time             0
weather_condition    0
day_of_week          0
is_holiday           0
event                0
pollution_level      0
car_count            0
bus_count            0
truck_count          0
motorcycle_count     0
is_weekend           0
hour_of_day          0
dtype: int64

In [77]:
columns_to_convert = [
    'record_id', 'intersection_id', 'vehicle_count', 'signal_cycle_time', 
    'green_time', 'yellow_time', 'red_time', 'car_count', 'bus_count', 
    'truck_count', 'motorcycle_count', 'event', 'is_holiday', 'is_weekend', 
    'hour_of_day'
]

for col in columns_to_convert:
    df[col] = df[col].astype(int)

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9981 entries, 0 to 10079
Data columns (total 23 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   record_id          9981 non-null   int32
 1   timestamp          9981 non-null   datetime64[ns]
 2   intersection_id    9981 non-null   int32
 3   intersection_name  9981 non-null   object
 4   latitude           9981 non-null   float64
 5   longitude          9981 non-null   float64
 6   vehicle_count      9981 non-null   int32
 7   average_speed      9981 non-null   float64
 8   signal_cycle_time  9981 non-null   int32
 9   green_time         9981 non-null   int32
 10  yellow_time        9981 non-null   int32
 11  red_time           9981 non-null   int32
 12  weather_condition  9981 non-null   object
 13  day_of_week        9981 non-null   object
 14  is_holiday         9981 non-null   int32
 15  event              9981 non-null   int32
 16  pollution_level    9981 non-null   float64
 17  car_count          9981 non-null   int32
 18  bus_count          9981 non-null   int32
 19  truck_count        9981 non-null   int32
 20  motorcycle_count   9981 non-null   int32
 21  is_weekend         9981 non-null   int32
 22  hour_of_day        9981 non-null   int32
dtypes: datetime64[ns](1), float64(4), int32(15), object(3)
memory usage: 1.3+ MB

In [79]:
# Save the modified DataFrame to a new CSV file
df.to_csv('Prayagraj_Traffic_Data_Cleaned.csv', index=False)

print("All changes have been saved to 'Prayagraj_Traffic_Data_Cleaned.csv'")

All changes have been saved to 'Prayagraj_Traffic_Data_Cleaned.csv'

In [80]:
data = pd.read_csv('Prayagraj_Traffic_Data_Cleaned.csv')
data.shape

(9981, 23)