In [18]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)

In [19]:
df = pd.read_csv('Prayagraj_Traffic_Data.csv')
df.sample(25)

,record_id,timestamp,intersection_id,intersection_name,latitude,longitude,vehicle_count,average_speed,signal_cycle_time,green_time,yellow_time,red_time,weather_condition,day_of_week,is_holiday,event,pollution_level,car_count,bus_count,truck_count,motorcycle_count
9648,2344.0,2023-01-02 15:00:00,4.0,Tagore Town,25.4675,81.8867,104.0,31.97,120.0,56.0,7.0,57.0,Clear,Monday,0.0,NaN,2.08,67.0,13.0,6.0,18.0
1594,5708.0,2023-01-04 23:00:00,8.0,Jhunsi,25.4326,81.9061,145.0,31.00,120.0,59.0,2.0,59.0,Clear,Wednesday,0.0,NaN,2.39,90.0,9.0,11.0,35.0
7188,8192.0,2023-01-06 16:30:00,2.0,Katra,25.4550,81.8463,124.0,33.14,120.0,59.0,4.0,57.0,Clear,Friday,0.0,NaN,2.13,83.0,11.0,6.0,24.0
5489,6719.0,2023-01-05 15:50:00,9.0,MNNIT Gate,25.4920,81.8639,49.0,39.90,120.0,58.0,5.0,57.0,Heatwave,Thursday,1.0,NaN,0.71,33.0,2.0,3.0,11.0
1733,4414.0,2023-01-04 01:30:00,4.0,Tagore Town,25.4675,81.8867,116.0,28.87,120.0,65.0,4.0,51.0,Fog,Wednesday,0.0,NaN,2.09,73.0,11.0,7.0,25.0
4299,3063.0,2023-01-03 03:00:00,3.0,Chowk,25.4314,81.8437,69.0,39.67,120.0,68.0,6.0,46.0,Clear,Tuesday,0.0,NaN,1.28,41.0,6.0,6.0,16.0
9249,8535.0,2023-01-06 22:10:00,5.0,Naini Bridge,25.4088,81.8592,152.0,32.11,120.0,81.0,5.0,34.0,Clear,Friday,0.0,NaN,3.26,85.0,15.0,21.0,31.0
7931,3667.0,2023-01-03 13:00:00,7.0,Phaphamau,25.4945,81.8686,102.0,33.36,120.0,63.0,6.0,51.0,Clear,Tuesday,0.0,NaN,1.90,60.0,9.0,9.0,24.0
612,6936.0,2023-01-05 19:30:00,6.0,Allahabad Junction,25.4358,81.8307,115.0,29.06,120.0,62.0,4.0,54.0,Cold Wave,Thursday,1.0,NaN,2.17,72.0,11.0,9.0,23.0
5594,9453.0,2023-01-07 13:30:00,3.0,Chowk,25.4314,81.8437,90.0,35.37,120.0,53.0,5.0,62.0,Clear,Saturday,0.0,NaN,1.95,51.0,12.0,8.0,19.0
964,9562.0,2023-01-07 15:20:00,2.0,Katra,25.4550,81.8463,60.0,40.96,120.0,62.0,4.0,54.0,Clear,Saturday,0.0,NaN,1.01,40.0,3.0,6.0,11.0
563,6404.0,2023-01-05 10:40:00,4.0,Tagore Town,25.4675,81.8867,106.0,36.86,120.0,58.0,6.0,56.0,Clear,Thursday,1.0,NaN,2.41,61.0,NaN,17.0,17.0
9950,6444.0,2023-01-05 11:20:00,4.0,Tagore Town,25.4675,81.8867,63.0,41.68,120.0,54.0,4.0,62.0,Clear,Thursday,1.0,NaN,1.20,40.0,8.0,NaN,13.0
6049,2511.0,2023-01-02 17:50:00,1.0,Civil Lines,25.4486,81.8333,220.0,26.75,120.0,80.0,6.0,34.0,Clear,Monday,0.0,NaN,4.96,134.0,27.0,27.0,32.0
1190,19.0,2023-01-01 00:10:00,9.0,MNNIT Gate,25.4920,81.8639,36.0,46.53,120.0,60.0,5.0,55.0,Clear,Sunday,1.0,NaN,0.78,26.0,4.0,4.0,2.0
9816,2110.0,2023-01-02 11:00:00,10.0,Minto Park,25.4352,81.8820,117.0,33.21,120.0,62.0,6.0,52.0,Clear,Monday,0.0,NaN,2.40,71.0,13.0,11.0,22.0
259,1131.0,2023-01-01 18:50:00,1.0,Civil Lines,25.4486,81.8333,91.0,25.84,120.0,68.0,6.0,46.0,Heavy Rain,Sunday,1.0,New Year Celebration,2.00,55.0,13.0,7.0,16.0
7462,2296.0,2023-01-02 14:10:00,6.0,NaN,25.4358,81.8307,70.0,41.48,120.0,54.0,5.0,61.0,Clear,Monday,0.0,NaN,1.25,49.0,7.0,3.0,11.0
8906,10046.0,2023-01-07 23:20:00,6.0,Allahabad Junction,25.4358,81.8307,66.0,40.44,120.0,64.0,5.0,51.0,Cold Wave,Saturday,0.0,NaN,1.36,36.0,9.0,4.0,17.0
9484,3999.0,2023-01-03 18:30:00,NaN,MNNIT Gate,25.4920,81.8639,154.0,28.11,120.0,86.0,5.0,29.0,Clear,Tuesday,0.0,NaN,3.15,88.0,15.0,18.0,33.0
1680,7568.0,2023-01-06 06:00:00,8.0,Jhunsi,25.4326,81.9061,101.0,38.96,120.0,53.0,4.0,63.0,Clear,Friday,0.0,NaN,2.21,52.0,12.0,12.0,25.0
8298,6500.0,2023-01-05 12:10:00,10.0,Minto Park,25.4352,81.8820,90.0,38.42,120.0,60.0,6.0,54.0,Clear,Thursday,1.0,NaN,1.88,54.0,9.0,11.0,16.0
7396,3447.0,2023-01-03 09:20:00,7.0,Phaphamau,25.4945,81.8686,147.0,20.78,120.0,65.0,4.0,51.0,Heavy Rain,Tuesday,0.0,NaN,2.82,89.0,7.0,24.0,27.0
9352,4416.0,2023-01-04 01:30:00,6.0,Allahabad Junction,25.4358,81.8307,78.0,29.37,120.0,52.0,5.0,63.0,Fog,Wednesday,0.0,NaN,1.45,52.0,4.0,11.0,11.0
3954,4309.0,2023-01-03 23:40:00,9.0,MNNIT Gate,25.4920,81.8639,89.0,31.54,120.0,62.0,6.0,52.0,Light Rain,Tuesday,0.0,NaN,1.72,50.0,8.0,9.0,22.0

In [20]:
df.isnull().sum()

record_id              98
timestamp              97
intersection_id        92
intersection_name     117
latitude              106
longitude             116
vehicle_count         112
average_speed          74
signal_cycle_time     108
green_time             92
yellow_time            89
red_time              102
weather_condition      78
day_of_week            94
is_holiday            104
event                9220
pollution_level       105
car_count              97
bus_count              95
truck_count           106
motorcycle_count      100
dtype: int64

In [21]:
# Function to generate a unique random ID
def generate_unique_random_id(existing_ids, low=1, high=10000):
    while True:
        random_id = np.random.randint(low, high)
        if random_id not in existing_ids: 
            return random_id

# Assuming 'df' is your dfFrame
existing_ids = set(df['record_id'].dropna())  # Get existing Record IDs without missing values
df['record_id'] = df['record_id'].apply(
    lambda x: generate_unique_random_id(existing_ids) if pd.isnull(x) else x
)

# Convert 'timestamp' column to DateTime format and drop rows with missing timestamps
df['timestamp'] = pd.to_datetime(df['timestamp'], errors='coerce')
df.dropna(subset=['timestamp'], inplace=True)

In [22]:
# Mapping between intersection names and IDs
area_to_id_map = {
    'Allahabad Junction': 6, 'Naini Bridge': 5, 'Chowk': 3, 'Tagore Town': 4,
    'Katra': 2, 'Phaphamau': 7, 'Minto Park': 10, 'MNNIT Gate': 9, 
    'Civil Lines': 1, 'Jhunsi': 8
}

# Fill missing 'intersection_id' using 'intersection_name' mapping
df['intersection_id'] = df['intersection_name'].map(area_to_id_map).fillna(df['intersection_id'])

# Fill missing 'intersection_name' using reverse mapping from 'intersection_id'
df['intersection_name'] = df['intersection_id'].map({v: k for k, v in area_to_id_map.items()}).fillna(df['intersection_name'])

# Resulting df Frame
print(df)

       record_id           timestamp  intersection_id   intersection_name  \
0         9926.0 2023-01-07 21:20:00              6.0  Allahabad Junction
1         8595.0 2023-01-06 23:10:00              5.0        Naini Bridge
2          673.0 2023-01-01 11:10:00              3.0               Chowk
3         8744.0 2023-01-07 01:40:00              4.0         Tagore Town
4          316.0 2023-01-01 05:10:00              6.0  Allahabad Junction
...          ...                 ...              ...                 ...
10075     7564.0 2023-01-06 06:00:00              4.0         Tagore Town
10076     6662.0 2023-01-05 15:00:00              2.0               Katra
10077     3105.0 2023-01-03 03:40:00              5.0        Naini Bridge
10078     5489.0 2023-01-04 19:20:00              9.0          MNNIT Gate
10079     6335.0 2023-01-05 09:30:00              5.0        Naini Bridge

       latitude  longitude  vehicle_count  average_speed  signal_cycle_time  \
0       25.4358    81.8307           75.0          39.72              120.0
1       25.4088    81.8592          139.0          30.33              120.0
2       25.4314    81.8437           20.0          53.28              120.0
3       25.4675    81.8867           21.0          36.06              120.0
4       25.4358    81.8307           41.0          47.21              120.0
...         ...        ...            ...            ...                ...
10075   25.4675    81.8867           23.0          52.53              120.0
10076   25.4550    81.8463           34.0          53.72              120.0
10077   25.4088    81.8592           22.0          40.91              120.0
10078   25.4920    81.8639          273.0          21.58              120.0
10079   25.4088    81.8592          114.0          33.92              120.0

       green_time  yellow_time  red_time weather_condition day_of_week  \
0            63.0          4.0      53.0             Clear    Saturday
1            51.0          4.0      65.0             Clear      Friday
2            69.0          5.0      46.0             Clear      Sunday
3            59.0          4.0      57.0        Heavy Rain    Saturday
4             NaN          5.0      54.0             Clear      Sunday
...           ...          ...       ...               ...         ...
10075        50.0          5.0      65.0             Clear      Friday
10076        63.0          5.0      52.0             Clear    Thursday
10077        60.0          5.0      55.0               Fog     Tuesday
10078        82.0          4.0      34.0        Light Rain   Wednesday
10079        62.0          5.0      53.0             Clear    Thursday

       is_holiday              event  pollution_level  car_count  bus_count  \
0             0.0                NaN             1.21       48.0        4.0
1             0.0                NaN             2.86       89.0       13.0
2             1.0                NaN             0.34       15.0        1.0
3             0.0                NaN             0.54       12.0        4.0
4             1.0                NaN             0.86       26.0        6.0
...           ...                ...              ...        ...        ...
10075         0.0  Local Market Fair             0.43       14.0        2.0
10076         1.0                NaN             0.57       20.0        4.0
10077         0.0                NaN             0.41       13.0        0.0
10078         0.0                NaN             5.58      167.0       26.0
10079         1.0                NaN             2.34       68.0       10.0

       truck_count  motorcycle_count
0              6.0              17.0
1             17.0              20.0
2              2.0               2.0
3              2.0               3.0
4              2.0               7.0
...            ...               ...
10075          2.0               5.0
10076          0.0              10.0
10077          5.0               4.0
10078         32.0              48.0
10079         15.0              21.0

[9983 rows x 21 columns]

In [23]:
# Latitude Mapping
area_to_latitude_map = {
    'Allahabad Junction': 25.4358, 'Naini Bridge': 25.4088, 'Chowk': 25.4314, 'Tagore Town': 25.4675,
    'Katra': 25.4550, 'Phaphamau': 25.4945, 'Minto Park': 25.4352, 'MNNIT Gate': 25.4920, 
    'Civil Lines': 25.4486, 'Jhunsi': 25.4326
}

df['latitude'] = df['intersection_name'].map(area_to_latitude_map).fillna(df['latitude'])

# Longitude Mapping
area_to_longitude_map = {
    'Allahabad Junction': 81.8307, 'Naini Bridge': 81.8592, 'Chowk': 81.8437, 'Tagore Town': 81.8867,
    'Katra': 81.8463, 'Phaphamau': 81.8686, 'Minto Park': 81.8820, 'MNNIT Gate': 81.8639, 
    'Civil Lines': 81.8333, 'Jhunsi': 81.9061
}

df['longitude'] = df['intersection_name'].map(area_to_longitude_map).fillna(df['longitude'])

In [24]:
# Step 1: Calculate mean values for each intersection_name
mean_values = df.groupby('intersection_name')[['vehicle_count', 'pollution_level', 'car_count', 'bus_count', 'truck_count', 'motorcycle_count']].mean()

# Step 2: Fill missing values for the specified columns using mean values
for col in ['vehicle_count', 'pollution_level', 'car_count', 'bus_count', 'truck_count', 'motorcycle_count']:
    df[col] = df.apply(
        lambda row: mean_values.loc[row['intersection_name'], col] if pd.isnull(row[col]) else row[col], axis=1
    )

# Step 3: Fill missing values in 'average_speed' with the overall mean
df['average_speed'] = df['average_speed'].fillna(df['average_speed'].mean())

In [25]:
# Replace missing values in 'signal_cycle_time' with a constant value
df['signal_cycle_time'] = df['signal_cycle_time'].fillna(120.0)

# List of columns to fill with their mean
columns_to_fill = ['green_time', 'yellow_time', 'red_time']

# Replace missing values in each of these columns with their respective mean
for col in columns_to_fill:
    df[col] = df[col].fillna(df[col].mean())

In [26]:
# Replace missing values in 'weather_condition' with its mode
weather_mode = df['weather_condition'].mode()[0]  # Find the mode (most frequent value)
df['weather_condition'] = df['weather_condition'].fillna(weather_mode)

In [27]:
#  Define the mapping for days of the week
days_mapping = {
    'Monday': 1,
    'Tuesday': 2,
    'Wednesday': 3,
    'Thursday': 4,
    'Friday': 5,
    'Saturday': 6,
    'Sunday': 7
}

#  Replace the values in the 'day_of_week' column directly
df['day_of_week'] = df['day_of_week'].map(days_mapping)

In [28]:
#  Define the mapping dictionary
event_mapping = {
    np.nan: 0,  # Handle NaN explicitly
    'New Year Celebration': 1,
    'Roadwork': 2,
    'Local Market Fair': 3,
    'Accident': 4
}

#  Replace the values in the 'event' column directly
df['event'] = df['event'].map(event_mapping).fillna(0).astype(int)

In [29]:
# Extract day of the week from the 'timestamp' column
df['day_of_week'] = df['timestamp'].dt.day_name()

# Assign 'is_holiday' based on whether the day is Sunday
df['is_holiday'] = df['day_of_week'].map({"Sunday": 1}).fillna(0)

# Drop rows with any remaining missing values
df.dropna(inplace=True)

In [30]:
# Create the 'is_weekend' column based on the 'day_of_week' column
df['is_weekend'] = df['day_of_week'].map({'Saturday': 1, 'Sunday': 1}).fillna(0).astype(int)

# Extract the hour from the 'timestamp' column and create a new column 'hour_of_day'
df['hour_of_day'] = df['timestamp'].dt.hour

In [31]:
df.isnull().sum()

record_id            0
timestamp            0
intersection_id      0
intersection_name    0
latitude             0
longitude            0
vehicle_count        0
average_speed        0
signal_cycle_time    0
green_time           0
yellow_time          0
red_time             0
weather_condition    0
day_of_week          0
is_holiday           0
event                0
pollution_level      0
car_count            0
bus_count            0
truck_count          0
motorcycle_count     0
is_weekend           0
hour_of_day          0
dtype: int64

In [32]:
# Save the modified DataFrame to a new CSV file
df.to_csv('Prayagraj_Traffic_Data_Cleaned.csv', index=False)

print("All changes have been saved to 'Prayagraj_Traffic_Data_Cleaned.csv'")

All changes have been saved to 'Prayagraj_Traffic_Data_Cleaned.csv'

In [33]:
data = pd.read_csv('Prayagraj_Traffic_Data_Cleaned')
data.shape

(9981, 23)